[package]
name = "ersha-dispatch"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/ersha-os/ersha-os"

[dependencies]
ersha-core = { path = "../ersha-core" } 
ulid = "1.1"
async-trait = "0.1"
jiff = "0.2.18"
serde_json = "1"
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread"] }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "macros", "migrate"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tempfile = "3.24.0"
