[package]
name = "server"
version = "0.1.1"
edition = "2024"

[dependencies]
ersha-edge = { path = "../.." }

postcard = "1.1.3"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["full"] }
ulid = "1.2.1"

[workspace]

