[package]
name = "ersha-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ordered-float.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
ulid.workspace = true
jiff.workspace = true
