[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
ersha-edge = { path = "../../ersha-edge" }

postcard = "1.1.3"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["full"] }

[workspace]

