[server]
rpc_addr = "0.0.0.0:9000"
http_addr = "0.0.0.0:8080"

[registry]
type = "clickhouse"
url = "http://localhost:8123"
database = "ersha_test"

[tls]
cert = "./keys/server.crt"
key = "./keys/server.key"
root_ca = "./keys/root_ca.crt"
domain = "localhost"
