[server]
rpc_addr = "0.0.0.0:9000"
http_addr = "0.0.0.0:8080"

[registry]
type = "memory"

# To use SQLite instead:
# [registry]
# type = "sqlite"
# path = "ersha-prime.db"

[tls]
cert = "./keys/server.crt"
key = "./keys/server.key"
root_ca = "./keys/root_ca.crt"
domain = "localhost"
